// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

// User represents a row in the users table.
type User struct {
	ID   int32        `json:"id"`
	Name string       `json:"name"`
	Dob  time.Time    `json:"dob"`
}

// NullString is a helper for nullable strings.
type NullString = sql.NullString
